version: "3"

services:
  acme.sh:
    image: neilpang/acme.sh
    container_name: acme.sh
    restart: always
    command: daemon
    environment:
      - CF_Key=${CF_KEY}
      - CF_Email=${CF_EMAIL}
    volumes:
      - ./acme/certs/:/acme.sh

  nginx:
    image: nginx
    restart: always
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./acme/certs/:/etc/nginx/certs
      - ./nginx/conf.d:/etc/nginx/conf.d
      - ./nginx/log:/var/log/nginx
      - ./nginx/www:/var/www
      - ../sites:/app/sites
    depends_on:
      - rsshub
      - alist

  rsshub:
    # two ways to enable puppeteer:
    # * comment out marked lines, then use this image instead: diygod/rsshub:chromium-bundled
    # * (consumes more disk space and memory) leave everything unchanged
    image: diygod/rsshub
    restart: always
    expose:
      - 1200
    environment:
      NODE_ENV: production
      CACHE_TYPE: redis
      REDIS_URL: "redis://redis:6379/"
      PUPPETEER_WS_ENDPOINT: "ws://browserless:3000" # marked
    depends_on:
      - redis
      - browserless # marked

  browserless:
    # marked
    image: browserless/chrome # marked
    restart: always # marked
    ulimits:
      # marked
      core:
        # marked
        hard: 0 # marked
        soft: 0 # marked

  redis:
    image: redis:alpine
    restart: always
    volumes:
      - redis-data:/data

  alist:
    image: 'xhofe/alist:latest'
    restart: always
    volumes:
      - ./alist/data:/opt/alist/data
    expose:
      - 5244
    environment:
      - PUID=0
      - PGID=0
      - UMASK=022
    container_name: alist

  chatgpt:
    build: ./chatgpt
    restart: always
    container_name: chatgpt

volumes:
  redis-data:
